

apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: emp
spec:
  groups:
  - dev
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FqQ0NBVklDQVFBd0pURVJNQThHQTFVRUF3d0laVzF3Ykc5NVpXVXhFREFPQmdOVkJBb01CMkpwZEc1aApiV2t3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGNNTW8wbUhLK1k4TmgxZ3Y0Cjd1M29RVHNqRzFHZktyamVyYXp1RVlFTnJ2NVpZWWI1SlJpemNMc21LM3luRTZGVEJ6RmgxcWFIZE9uR0dEVjgKUVVpaW0yNnJ2YVQ1RFZQTkozNlB1RXJubmVzZlhmaDZVeGJRRkY0cUVTQ3c4ejA5MTZqRVg2bGZHMnpna1kySAp5akRMamx2djRrbmpVVlh0Um00QUEwbVB3aXF4d1A5dklrNUNWaVhqYzl5bmdsZFE5TWpUNTEvMmJGN0cxL2s0ClVCWlZ5MGJmQVRmeFV5RGpmeVhtZWhLY1BrWEJPQnFPUTRXaHdoeHpaUXpTWHppTnRvN0h4YlVicUtWUWhEMWMKRW94bUNKNHRzU0crZEtkcVY3TVRYVG5oQUp5TWZmeUYyMjg5S1FzMkJqbFhZZG9XWU9BODhzZWxTdjRINUp1dApuUVZSQWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbDY3WVl4eWp3RFZ1WUhsU2Z4ODMveTZZClUrTFFpRUdBQ3ljK29zSDF1UHJOMHJ6d1B1WUV4TjA4S09vdXlta2pITnNTT0ZoUjBxS3hBbkc5VFQ2UkY4UWEKQTljYjFNQ1pieXZKVUNaUG13OVZlbTlSVXloeCtudi92TDdqOEdDRmNKbW1DVkpYVllGZ0lkZ0lndSswSmxHSwppOE5tQjBpYzJoMENnb1c1OFhvbEptS1pqMGxnOGU2Yml2SWtSOUs2NFhveGpkanRlQnBtVm5JRTFhOG1pMGJrCjdWZkMwaVkvM0IxcTB6b1lXZ1cyOFhtb3l5VHRMVzRHR1R3V1MyeEhkU0tVWEJhUGVkazNKbzlhMzlDMjJTMjAKWERxTTV4QWVLTmZ4L3krQmw4dVByR3lrSXFzOVBYZlVZSGlKcjJsQ2N2eDRGZEdWUFgwQ1VKRDV2Z1NIM1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  
  usages:
  - client auth