apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: emp
spec:
  groups:
  - dev
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2lqQ0NBWElDQVFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeApJVEFmQmdOVkJBb01HRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLRW9ibi90UG91aTc4bVVMTnRxTDZZNDlwNjlKR3ZVR3hReWd2Q3EKSTFBOWFqWSt1N1d6OHhQYWgzZHBiQVpOKytKS0U1U2sxSm1QR05mOUVWc1JSRzdSTHNaN3pSaGtXMTNTVFB3UQpWalFoVDl4WmlSOFo3L2FsMjF4RWR6N0JpeittUk0wTHh2eHRzcVc4WlEwaitCc1JBRkFmU2lNSmxBMTlleEVjCnZxL2lHb0lQUWltVk5QQUJDRHdJRjFzdWJpZXZaNjdHYVRnR1Bmb2lmWnRKVmlZYTYyYXN6d25Dd2pQVkdlak0KSHgrUEZ0NnNTS1VLKzBtQ0tsUlFnaTB5RzVrbFU0akt4VXdBb0tacGoyMWVZOTE4bWFQVjBCeXZPNzdDTkx2awpnZGk3Q1B1dHBXMElxOUxYZVhpWlZkVUtNUDZwV3oreFl6MUZPTi9jUFpDSnQvTUNBd0VBQWFBQU1BMEdDU3FHClNJYjNEUUVCQ3dVQUE0SUJBUUNRZHBjK0MrMXJWMGFCaVllMEpaTWRPRXdCSXJpamJYVWJuRW9sUm9YY1l4aHoKdWFrTm9wSFBRbnFxM2VWME1kVFNMWWFlVERYWnUxQktqZjhoNnluei82MUJSSVpjZ0VsaENxWVhNeWRBQ0Z5ZApSb29KYzVRQjFVMEVTOUlxR0pncklYNjZVcGJycW5KMlNVUHJqV2Z2VHFydW5NQlRRcGVNMkRsOERvUGdicStCCkVNYXdoMlVhaUl5dklpWWtkVDJhUWt6STJDTktuVWdkQmtPK0ZMaG9OZVBPK2FRbEJZaC9pVlhxaGdkeDZ3cDMKNzcvNlhXWXZ3Y0I0d0g0U0owZ0NyTUFreFA4dkphVUhhcGoySVl2N3h5MDlrUE9BV1Q1dlhzaXRPMTJBTnk2dQpOZ3NMUHZkNUh3Ulh5VWNlNkFtSFZ1UXkvTHJraXVFTEgwRGpFT3ZLCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  
  usages:
  - client auth

# kubectl get csr my-svc.my-namespace -o jsonpath='{.status.certificate}' \
#    | base64 --decode > server.crt

#kubectl get csr emp -o jsonpath='{.status.certificate}'| base64 -d > emp.crt


1. openssl genrsa -out employee.key 2048
2. openssl req -new -key employee.key -out employee.csr -subj "/CN=employee/O=bitnami"
3. Create CSR using this -> cat employee.csr | base64 | tr -d "\n"
4. kubectl certificate approve emp
5. kubectl get csr emp -o jsonpath='{.status.certificate}'| base64 -d > employee.crt
6. kubectl get csr emp -o jsonpath='{.status.certificate}'| base64 -d > employee.crt
7. kubectl config set-credentials employee --client-certificate=employee.crt  --client-key=employee.key
8. kubectl config set-context employee-context --cluster=minikube --namespace=office --user=employee
9. Create Role