apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: emp-bind
    namespace: office
subjects:
    - kind: User 
      name: employee 
      apiGroup: ""
roleRef:
    kind: Role
    name:  emp-role
    apiGroup: ""