apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: office
  name: emp-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["deployment"]
  verbs: ["get", "watch", "list"]