apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority: /Users/lokendrab.chhetri/.minikube/ca.crt #location of .crt
    server: https://192.168.99.102:8443
  name: minikube


contexts:
- name: dev-ctx
  context: 
    cluster: minikube
    namespace: dev
    user: my-kube-admin

users:
- name: emp
  user:
    client-certificate: emp.crt 
    client-key: emp.key 

# kubectl config set-credentials emp --client-key=emp.key --client-certificate=emp.crt --embed-certs=true
# kubectl config set-context emp --cluster=minikube --user=dev-ctx
# kubectl config use-context emp

# kubectl config set-context --current --namespace=dev