# apiVersion: v1
# kind: Pod
# metadata:
#   name: fresco-nginx-pod
# spec:
#   volumes:
#   - name: foo
#     secret:
#       secretName: fresco-secret
#   containers:
#   - name: fresco-nginx-container
#     image: nginx
#     volumeMounts: 
#     - name: foo
#       mountPath: "/etc/test"
#     env:
#     - name: SERVER_URL_ENV
#       valueFrom: 
#         configMapKeyRef: 
#           name: fresco-config
#           key: SERVER_URL

apiVersion: v1
kind: Pod
metadata:
  name: fresco-nginx-pod
spec:
  volumes:
  - name: foo
    persistentVolumeClaim:
        claimName: fresco-pvc
  containers:
  - name: fresco-nginx-container
    image: nginx
    volumeMounts: 
    - name: foo
      mountPath: "/usr/share/nginx/html"
    env:
    - name: SERVER_URL_ENV
      valueFrom: 
        configMapKeyRef: 
          name: fresco-config
          key: SERVER_URL

